### ISSUE TITLE
Linux version

### ISSUE THREAD

**Issue by RaptaG** [overwolf/detection-tool#1]
The attack targeted Linux too, in the releases there's only a .exe file

**Comment by cravl-dev** [comment]
`rm -rv ~/.config/.data` would be a start, that should tell you if it finds and removes the stage 1 binary. It won't remove the systemd unit files it creates to autostart the malware, but those should be harmless, as far as I've read they aren't made to do anything sinister on their own. Mods may still also be infected.

**Comment by turbosmurfen** [comment]
I have been looking around for Linux scanning. But I found the people behind the findings GitHub page here: https://github.com/fractureiser-investigation/fractureiser. I have found automatic checks too from their GitHub. But sure the manually checks exists.

**Comment by furtabs** [comment]
I can probably port the tool. Just give me like a few

**Comment by furtabs** [comment]
https://github.com/EndangeredNayla/fractureiser-detector/tree/master

**Comment by eitambelahousky** [comment]
Latest version now supports Linux

https://github.com/overwolf/detection-tool/releases/tag/0.0.2
