### ISSUE TITLE
am i safe?

### ISSUE THREAD

**Issue by PlatinumOx** [overwolf/detection-tool#12]
i downloaded the detection tool and clicked scan, it said "no malware detected on your machine" or something like that , am i safe to play minecraft?

**Comment by Sunconure11** [comment]
Yes

**Comment by PlatinumOx** [comment]
cool, so am i safe as long as i dont download any mods?

**Comment by eitambelahousky** [comment]
Make sure to follow the instructions at:
https://support.curseforge.com/en/support/solutions/articles/9000228509-june-2023-infected-mods-detection-tool
Once you complete that you can play and download mods
