### ISSUE TITLE
is C:\Users\acer\AppData\Roaming\Microsoft\Internet Explorer\UserData\Low safe?

### ISSUE THREAD

**Issue by fakeman628** [overwolf/detection-tool#13]
i saw a file named "internet explorer" which had a thing called "screen sharer" my apps on my hotbar. and some more info about me

**Comment by eitambelahousky** [comment]
This is an artifacts path used by the Internet Explorer browser. If you have concerns about it I suggest scanning it with an Antivirus software.
In any case the tool doesn't consider it a suspicious path
