### ISSUE TITLE
Support for non-standard minecraft location

### ISSUE THREAD

**Issue by vico93** [overwolf/detection-tool#3]
Does this tool support minecraft to be present in other locations (like specified by `--workDir` argument for Mojang's launcher and/or game directiories for each installation) or it need to be on the default folder (`%AppData%\.minecraft`)?

**Comment by itssimple** [comment]
The tool doesn't check any mods, it checks if you're already infected, so it doesn't catch the <kbd>stage 0</kbd> part.

**Comment by vico93** [comment]
uh sorry then
