### ISSUE TITLE
aarch64 support

### ISSUE THREAD

**Issue by WoeyJonkers** [overwolf/detection-tool#8]
Assuming fractureiser can run on aarch64 (if not, can you let me know? i've got servers running on aarch64 and i want to be absolutely sure they're good to go), it is important that this tool also supports aarch64 so everyone can use it. I'm not sure how difficult it is to do that but it would be very helpful.

**Comment by Athsmooth** [comment]
I use Arch and I would like compatibility too

**Comment by rainyskye** [comment]
> I use Arch and I would like compatibility too

are you talking about arch linux or aarch64 (arm)?

if you're using arch linux it should work fine.

**Comment by Athsmooth** [comment]
@rainyskye yes I use Arch, when I open it, it says, "Choose an application to open the file link" which makes me think it is not compatible, I might just need a certain application though for compatibility.

**Comment by WoeyJonkers** [comment]
@Athsmooth if you're having trouble running it on Arch (the distro, not the cpu architecture), try doing `chmod +x /path/to/detection-tool-console-0-0-2-linux` and then running it again.

If that still doesn't work, try running the tool from a terminal, assuming that's not what you were doing already. If it STILL doesn't work after that, then idk, my nerd skills don't extend that far lol

**Comment by Athsmooth** [comment]
Detected: NO
Malware was not detected on your machine

Ahh that's a relif it worked, I didn't think Linux had viruses but I guess they are out there. Thanks.
