### ISSUE TITLE
Does this tool scan external/all drives?

### ISSUE THREAD

**Issue by Nosnek199** [overwolf/detection-tool#9]
Does this tool scan all drives, or only the local C: drive.

**Comment by eitambelahousky** [comment]
The tool looks for the malware in specific locations where it will be found if the machine is infected

**Comment by dolphin-cat** [comment]
can we say if we moved our .minecraft to another place that all the things under .minecraft shall instead be under a custom path?

**Comment by eitambelahousky** [comment]
The tool doesn't look in the .minecraft dir so there is no need to do that
